server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/userservice_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


jwt:
  secret: ${JWT_SECRET}              # read from environment variable
  expiration: ${JWT_EXPIRATION:86400000}   # default 1 day if not set

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}       # read from environment variable
  auth-token: ${TWILIO_AUTH_TOKEN}         # read from environment variable
  from-number: ${TWILIO_PHONE_NUMBER}      # read from environment variable
  otp-expiry-minutes: ${TWILIO_OTP_EXPIRY:5}  # default 5 minutes if not set
